### ISSUE TITLE
ISO Fortran Environment Module and Default GNU Compilation

### ISSUE THREAD

**Issue by A-Mahler** [MQCPack/mqcPack#74]
When we compile mqc using the gfortran compiler, it flags a warning that the iso_fortran_env module and -fdefault-integer-8 are incompatible.  We should choose one of these options going forward, rather than ignoring the incompatibility warning.

I am inclined to remove the -fdefault-integer-8 flag from the gfortran compiliation steps, as the standard in MQC is to explicitly declare the intrinsic types with the iso_fortran_env module options.

**Comment by hphratchian** [comment]
This makes sense to me @A-Mahler. I'll assign this to you. Let me know if you need help running this build config change to ground.

**Comment by A-Mahler** [comment]
Examining the problem further, it appears that we should leave the -fdefault flags in place.  The benefit, as I understand it, in using these flags is to ensure that the intrinsic Fortran functions used in MQC (such as the square root function) have the same 64-bit precision as the MQC variables.  For the GNU compiler, it appears that the -fdefault flags are specifically used for this purpose.

The issue that is causing the warning is that the NUMERIC_STORAGE_SIZE constant in the ISO Fortran environment module is incompatible with these default flags in the GNU compiler.  However, we are not using this constant in MQC, nor do I see any need or benefit to using it.  Our use of the ISO Fortran environment module is restricted to the using the ISO standardized kind parameters (int32, int64, real64, etc.).

Thus, the resolution to this issue, I believe, is to restrict our usage of the ISO Fortran module to the standardized kind parameters, rather than importing the entire environment module.  This removes the warning, as we are no longer importing the NUMERIC_STORAGE_SIZE constant, and preserves the MQC standard of using the ISO Fortran environment kind parameters.
